### ISSUE TITLE
M4A and search by TIDAL link

### ISSUE THREAD

**Issue by vad62** [exislow/tidal-dl-ng#42] opened 2024-02-14 06:34 UTC
Make default conservation in the format of a flac or selection of format. When using files in ROON, M4A is not supported and has to be converted, doing unnecessary work, not all digital transports also support M4A. Also, if the maintenance of the release in the MQA is chosen, then there should be an identification mark of the format, it does not need to be redrawn, but leave as it is. The choice of 16/44.1 or HD-flac should only be for files in the HD-flac format. 
It’s also a good idea to add a search using a link from Tidal; searching by name is very inconvenient.
Thank you.

**Comment by exislow** [comment] 2024-02-14 06:59
Duplicate of https://github.com/exislow/tidal-dl-ng/issues/22#issuecomment-1923492562 and #37

I also do not quite understand what you exactly want. Either your translate app is bad (better use https://deepl.com/) or it just does not make sense to me.

Try to read the linked issues. If they do not cover all of your wishes please open another feature request issue, with very descriptive title and a proper description stating exactly what you are wishing / looking for. Thanks!

**Closed by exislow** 2024-02-14 06:59 UTC
