### ISSUE TITLE
[Bug] About every browser and antivirus gives virus and not to trust

### ISSUE THREAD

**Issue by mizwdev** [exislow/tidal-dl-ng#286] opened 2024-12-19 20:17 UTC
### What happened?

I'm still using 0.15 after every version shows virus and you can say what you want, but I won't install newer version before it is fixed.

### Version App

latest

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
Trojan:Win32/Suschil!rfn
```

### Your settings

```json
none
```

**Comment by orbittwz** [comment] 2024-12-20 05:53
probably to be merged with #231 .
newest version still flagged on my end.
until he removes the heuristics, this is the situation.

**Comment by exislow** [comment] 2024-12-20 14:49
Duplicate of #231

You do not need to install any version you do not like. Just ignore the update dialog on startup.

**Closed by exislow** 2024-12-20 14:49 UTC
Labels: bug
