### ISSUE TITLE
[Feature] Download 5.1 Content 

### ISSUE THREAD

**Issue by ryjayt** [exislow/tidal-dl-ng#173] opened 2024-08-12 10:10 UTC
### Current Situation

When Downloading it only dose it in stereo. 

### Suggestion / Feature Request

The Only 2 ressons i wanted TIDLE over spotify was 5.1 content but its not suported on PC Would love to be able to download it. The other reson was higer quality audio over spotify

**Comment by exislow** [comment] 2024-11-10 22:16
This should be implemented indeed. Feel free to get me a pull request for this.

**Comment by exislow** [comment] 2024-11-29 17:10
I think its some sort of a duplicate of #106. If not, feel free to reopen this issue again.

**Closed by exislow** 2024-11-29 17:10 UTC
Labels: enhancement
