### ISSUE TITLE
[Help] v0.21.2 - Win11 BitDefender cries...

### ISSUE THREAD

**Issue by ni-pa-ny** [exislow/tidal-dl-ng#262] opened 2024-11-30 16:48 UTC
### I need Help.

see screen

![2024 11 30 17_46_33](https://github.com/user-attachments/assets/880ef862-1eb9-463a-ac8a-4d9a0f6da62e)

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
see screen
```

**Comment by ni-pa-ny** [comment] 2024-11-30 17:06
solved by adding folder to exception list

**Comment by ryoko7** [comment] 2024-11-30 17:52
Duplicate of issue #231. Underlying issue may or may not have a fix

**Comment by lkjdsf65** [comment] 2024-12-01 01:16
![Captura de pantalla 2024-11-30 221436](https://github.com/user-attachments/assets/724b29ad-ce70-400f-9a88-49f9353107cd)

**Comment by exislow** [comment] 2024-12-01 17:20
Duplicate #231

**Closed by exislow** 2024-12-01 17:20 UTC
Labels: help wanted
