### ISSUE TITLE
[Bug] Download is slow compared to tidal-dl

### ISSUE THREAD

**Issue by dejl** [exislow/tidal-dl-ng#168] opened 2024-08-01 12:14 UTC
### What happened?

Hi

Compared to Tidal-DL GUI, downloading items is extremely slow..
Tidal-DL was super fast and maxing out my connection.

Is anyone else experiencing this?

### Version App

latest

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
N/A
```

**Comment by AhnTraeii** [comment] 2024-08-03 18:10
Hey,

yes I'm experiencing the same. I get about a 10th of my actual internet speed. I thought this might be a Tidal limiation but than remembered the speed of T-DL GUI too.

Also on Windows with the latest version of the app.

**Comment by blasf69** [comment] 2024-08-04 19:15
Me too I posted something a month ago about that but the speeds went back up so I looked dumb. Maybe tidal is throttling us

**Comment by tatoomana** [comment] 2024-08-12 11:22
Same here. I run side by side "tidal-dl-ng" and "Tidal-Media-Downloader-PRO".
Result : T-M-D-PRO is by far much faster than TDNG.

**Comment by tatoomana** [comment] 2024-08-13 03:40
After some tests, I found that the slow download is only if you select "hi_res" & "hi_res_lossless". In "high-lossless", the speed becomes very appreciable on my 300M fiber:
- on average 120 Mb/s in "high-lossless"
- on average 10 Mb/s in "hi_res" & "hi_res_lossless"

Test conducted on the same album

**Comment by dejl** [comment] 2024-08-13 18:39
> After some tests, I found that the slow download is only if you select "hi_res" & "hi_res_lossless". In "high_lossless", the speed becomes very appreciable on my 300M fiber:
> 
> * on average 120 Mb/s in "high_lossless"
> * on average 10 Mb/s in "hi_res" & "hi_res_lossless"
> 
> Test conducted on the same album

This would force downloading non hi res (up to 192 KHz)
at this point i'm assuming they are rate limiting bandwidth

**Comment by exislow** [comment] 2024-11-08 16:06
Duplicate of #153

**Closed by exislow** 2024-11-08 16:06 UTC
Labels: bug
